version: '3.9'

services:
  web:
    image: shlomi10/pdf-trivia-app:11
    container_name: pdf_trivia_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
