"""add file_key to invoices

Revision ID: bc6b8171f0dc
Revises: 39a5b174b718
Create Date: 2025-07-25 00:05:55.292025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6b8171f0dc'
down_revision: Union[str, Sequence[str], None] = '39a5b174b718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('file_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'file_key')
    # ### end Alembic commands ###
